name: build & unit test

on:
  push:
    branches:
      - release
      - hotfix
      - develop
      - feature/*
      - bugfix/*      
    tags:
      - '**'  

permissions:
  contents: write
  packages: write      

jobs:
  call-frontend-ci-workflow:
    uses: netcracker/qubership-apihub-ci/.github/workflows/frontend-ci.yaml@bugfix/npm-dist-tag-not-deleted

  echo-outputs:
    runs-on: ubuntu-latest
    needs: call-frontend-ci-workflow
    steps:
      - run: echo ${{ needs.call-frontend-ci-workflow.outputs.package_version }} ${{ needs.call-frontend-ci-workflow.outputs.npm_dist_tag }}