name: Frontend CI Workflow

on:
  push:
    branches:
      - release
      - develop
      - feature/*
      - bugfix/*
      - hotfix/*
    tags:
      - '**'
  delete:

permissions:
  contents: write
  packages: write      

jobs:
  call-frontend-ci-workflow:
    uses: netcracker/qubership-apihub-ci/.github/workflows/frontend-ci.yaml@feature/simplify-fe-wf 

  echo-outputs:
    runs-on: ubuntu-latest
    needs: call-frontend-ci-workflow
    steps:
      - run: echo ${{ needs.call-frontend-ci-workflow.outputs.package_version }} ${{ needs.call-frontend-ci-workflow.outputs.npm_dist_tag }}